(defun color-theme-late-night ()
  "Color theme by Alex Schroeder, created 2003-08-07.
This theme is for use late at night, with only little light in the room.
The goal was to make something as dark and subtle as the text console in
its default 80x25 state -- dark grey on black."
  (interactive)
  (let ((color-theme-is-cumulative t))
    (color-theme-dark-erc)
    (color-theme-dark-gnus)
    ;; (color-theme-dark-diff)
    ;; (color-theme-dark-eshell)
    (color-theme-dark-info)
    (color-theme-dark-font-lock)
    (color-theme-install
     '(color-theme-late-night
       ((background-color . "#000")
	(background-mode . dark)
	(background-toolbar-color . "#000")
	(border-color . "#000")
	(bottom-toolbar-shadow-color . "#000")
	(cursor-color	. "#888")
	(foreground-color . "#666")
	(top-toolbar-shadow-color . "#111"))
       (default ((t (nil))))
       (bold ((t (:bold t))))
       (button ((t (:bold t))))
       (custom-button-face ((t (:bold t :foreground "#999"))))
       (fringe ((t (:background "#111" :foreground "#444"))))
       (header-line ((t (:background "#333" :foreground "#000"))))
       (highlight ((t (:background "dark slate blue" :foreground "light blue"))))
       (holiday-face ((t (:background "#000" :foreground "#777"))))
       (isearch ((t (:foreground "pink" :background "red"))))
       (isearch-lazy-highlight-face ((t (:foreground "red"))))
       (italic ((t (:bold t))))
       (menu ((t (:background "#111" :foreground "#444"))))
       (minibuffer-prompt ((t (:foreground "555"))))
       (modeline ((t (:background "#111" :foreground "#444"))))
       (mode-line-inactive ((t (:background "#000" :foreground "#444"))))
       (modeline-buffer-id ((t (:background "#000" :foreground "#555"))))
       (modeline-mousable ((t (:background "#000" :foreground "#555"))))
       (modeline-mousable-minor-mode ((t (:background "#000" :foreground "#555"))))
       (region ((t (:background "dark cyan" :foreground "cyan"))))
       (secondary-selection ((t (:background "Aquamarine" :foreground "SlateBlue"))))
       (show-paren-match-face ((t (:foreground "white" :background "light slate blue"))))
       (show-paren-mismatch-face ((t (:foreground "white" :background "red"))))
       (tool-bar ((t (:background "#111" :foreground "#777"))))
       (tooltip ((t (:background "#333" :foreground "#777"))))
       (underline ((t (:bold t))))
       (variable-pitch ((t (nil))))
       (widget-button-face ((t (:bold t :foreground "#888"))))
       (widget-field-face ((t (:bold t :foreground "#999"))))))))